# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: project/project.proto for package 'gonex_project'

require 'grpc'
require 'project/project_pb'

module GonexProject
  module ProjectSvc
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gonex_project.ProjectSvc'

      rpc :createProject, ::GonexProject::CreateProjectRequest, ::GonexProject::ProjectResponse
      rpc :createTag, ::GonexProject::CreateTagRequest, ::GonexProject::TagResponse
      rpc :getProject, ::GonexProject::GetProjectRequest, ::GonexProject::ProjectResponse
    end

    Stub = Service.rpc_stub_class
  end
end
