# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: task/task.proto for package 'gonex_task'

require 'grpc'
require 'task/task_pb'

module GonexTask
  module TaskSvc
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gonex_task.TaskSvc'

      rpc :createTask, ::GonexTask::CreateTaskRequest, ::GonexTask::TaskResponse
      rpc :updateTask, ::GonexTask::UpdateTaskRequest, ::GonexTask::TaskResponse
      rpc :listTasks, ::GonexTask::ListTasksRequest, ::GonexTask::ListTasksResponse
    end

    Stub = Service.rpc_stub_class
  end
end
